- ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    group: "{{ ec2_security_group }}"
    count: "{{ ec2_instance_count }}"
    region: "{{ ec2_region }}"
    instance_tags:
            Name: "{{ ec2_tag }}"
  register: ec2
  
  
- name: Wait for SSH to come up
  wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
  with_items: "{{ ec2.instances }}"
           
       
    
- name: Add new instance to host group
  add_host:
        hostname: "{{ item.public_ip }}"
        groupname: redhat
  with_items: "{{ ec2.instances }}"
