- ec2:
    key_name: keypair1
    instance_type: t2.micro
    image: ami-f173cc91
    wait: yes
    group: devops_secgrp
    count: 1
    vpc_subnet_id: subnet-05e04162
    region: us-west-2
    assign_public_ip: yes
  register: ec2
  
- debug: var=ec2

- name: wait for SSH to come up
  wait_for:
            host: '{{ item.public_ip }}'
            port: 22
            delay: 60
            timeout: 300
            state: started
  with_items: '{{ ec2.instances }}'
  
  
- name: Add servers to host group
  add_host:
            hostname: '{{ item.public_ip }}'
            groupname: devops_secgrp
  with_items: '{{ ec2.instances }}'