---

- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: maven
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']


- name: Install Maven download directory (remote)
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ansible_data_path }}


- name: Download Maven (remote)
  tags: maven
  get_url: 
    dest={{ ansible_data_path }}/{{ maven_redis_filename }}
    url=http://www-us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    owner=0
    group=0
    mode=0644
    sha256sum={{ maven_redis_sum }}


- name: Install Maven installation directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_install_dir }}

# Ansible 2.1.X.Y bug with unpack https://github.com/ansible/ansible-modules-core/issues/3241
#- name: Install Maven - Fix Ansible Unpack Issue 3241
- command: tar -xvzf {{ ansible_data_path }}/{{ maven_redis_filename }} -C {{ maven_install_dir }}

#- name: Install Maven
#  tags: maven
#  unarchive:
#    src={{ ansible_data_path }}/{{ maven_redis_filename }}
#    dest={{ maven_install_dir }}
#    copy=no


- name: Install Maven bin directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_bin_path }}


- name: Install Maven binary
  tags: maven
  file:
    state=link
    force=true
    src={{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn
    dest={{ maven_bin_path }}/mvn
