---
# This task installs and enables apache on webservers
- name: ensure apache is installed
  yum: pkg=httpd state=latest
- name: ensure apache is running
  service: name=httpd state=running enabled=yes

- name: copy application code to document root
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart apache