---
repo_key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x4BD736A82B5C1B00'
repo_key_file: '4BD736A82B5C1B00.gpg'
  



cassandra-repo: 'deb http://www.apache.org/dist/cassandra/debian 20x main'


cluster_name: 'MyCluster'
data_file_directories:
    - '/var/lib/cassandra/data'
commitlog_directory: '/var/lib/cassandra/commitlog'
saved_caches_directory: '/var/lib/cassandra/saved_caches'
log_level: 'info'
